### ISSUE TITLE
RAID F1 and SHR may coexist

### ISSUE THREAD

**Issue by pengkui** [007revad/Synology_RAID-F1_SHR_switch#18]
After setting support_syno_hybrid_raid to "yes" and supportraidgroup to "no", it appears that RAID F1, SHR-1 and SHR-2 can coexist.  One can choose RAID F1 on SSD drives and SHR-1/2 on HDD drives on the same machine.

This seems to run against your README statement "Changing to RAID F1 disables SHR, and changing to SHR disables RAID F1."  Is there a reason to impose this mutual exclusiveness?

![RAID-synoinfo](https://github.com/007revad/Synology_RAID-F1_SHR_switch/assets/751825/1174fb5a-c86a-4db8-95f0-1ee5cadc1fa5)

![RAID-SHR](https://github.com/007revad/Synology_RAID-F1_SHR_switch/assets/751825/782b563b-0188-480c-a4fb-b60712588e7b)

![RAID-F1](https://github.com/007revad/Synology_RAID-F1_SHR_switch/assets/751825/2967eb47-f3a7-4f43-9ed4-0a88fa1e905b)

![RAID-SATA](https://github.com/007revad/Synology_RAID-F1_SHR_switch/assets/751825/ce876cd1-37da-4633-aef9-0acb50b36774)

**Comment by 007revad** [comment]
Thanks. And thank you for including screenshots.

> This seems to run against your README statement "Changing to RAID F1 disables SHR, and changing to SHR disables RAID F1." Is there a reason to impose this mutual exclusiveness?

From what I read on the Xpenology forum I thought they said that in DSM you could have RAID F1 or SHR but not both. I've never had 3 SATA SSDs to test it with.

Now I'm wondering if my script is just disabling and enabling SHR - and RAID-F1 is always enabled (on models that support RAID F1). Which raises the question of how to enable RAID F1 on other models.

**Comment by pengkui** [comment]
https://xpenology.com/forum/topic/9394-installation-faq/?tab=comments#comment-131458

This xpenology post suggests that "Note that SHR can be enabled on these platforms by modifying /etc.defaults/synoinfo.conf, with no impact to RAIDF1 functionality."

**Comment by 007revad** [comment]
> "The MDRAID modifications that enable RAIDF1 are compiled into the DSM kernel. The consumer-oriented DSM platforms do not contain those changes,"

That makes sense.

Before I saw your last comment I found some incorrect information here https://www.reddit.com/r/synology/comments/jueg8z/comment/gcbv9wp/ that said "RAIDF1 is an option compiled into their customized version of mdm, and therefore there is no way create a RAIDF1 on unsupported device."

After checking 112 different model's mdadm I found that all models include raidf1 in mdadm (even single drive Synology NAS!) so I knew that was wrong. 

So my raidf1_shr_switch script needs an update to make it just shr_switch

**Comment by pengkui** [comment]
How are you planning to change the script? 😄 

I noticed https://kb.synology.com/en-us/DSM/tutorial/What_is_RAID_Group
```
DSM 7.0 and above

On models with support for RAID groups
- RAID F1

On models without support for RAID groups
- RAID F1, SHR
```

If "models with support for RAID groups" can be signified by `supportraidgroup="no"`,

is it fair to assume the following outcomes?
- `supportraidgroup="no"` & `support_syno_hybrid_raid="yes"`: both F1 and SHR are available
- `supportraidgroup="yes"` & `support_syno_hybrid_raid="no"`: only F1 is available
- `supportraidgroup="yes"` & `support_syno_hybrid_raid="yes"`: only F1 is available

**Comment by pengkui** [comment]
This KB article https://kb.synology.com/en-us/DSM/tutorial/What_is_RAID_Group
especially the row "On models without support for RAID groups" where F1 and SHR are mentioned together
seems to suggest that the mutual exclusivity is between RAID group and SHR, not between F1 and SHR.

**Comment by 007revad** [comment]
> seems to suggest that the mutual exclusivity is between RAID group and SHR, not between F1 and SHR.

It does seem to suggest that. 

> How are you planning to change the script? 😄

I was going to remove all reference to RAID F1 and change it to either disable or enable SHR. But having read that page you linked I think I'll just change the RAID F1 text to RAID Group. So it will actually be Synology_RAID-Group_SHR_switch

> I noticed https://kb.synology.com/en-us/DSM/tutorial/What_is_RAID_Group
> 
> ```
> DSM 7.0 and above
> 
> On models with support for RAID groups
> - RAID F1
> 
> On models without support for RAID groups
> - RAID F1, SHR
> ```
> 
> If "models with support for RAID groups" can be signified by `supportraidgroup="no"`,
> 
> is it fair to assume the following outcomes?
> 
> * `supportraidgroup="no"` & `support_syno_hybrid_raid="yes"`: both F1 and SHR are available
> * `supportraidgroup="yes"` & `support_syno_hybrid_raid="no"`: only F1 is available
> * `supportraidgroup="yes"` & `support_syno_hybrid_raid="yes"`: only F1 is available

- The only "model" that has `supportraidgroup="no"` is VirtualDSM.
- The models that support RAID groups all have `supportraidgroup="yes"`
- The models that don't support RAID groups don't have any `supportraidgroup` setting in synoinfo.conf

It definitely looks like:
- You can have RAID Groups or SHR but not both.
- RAID F1 is always available (on models that support RAID F1).

I would take your scenario one step further to say:
* `supportraidgroup="no"` & `support_syno_hybrid_raid="yes"`: both F1 and SHR are available, but not RAID groups
* `supportraidgroup="yes"` & `support_syno_hybrid_raid="no"`: both F1 and RAID groups are available, but not SHR
* `supportraidgroup="yes"` & `support_syno_hybrid_raid="yes"`: both F1 and RAID groups are available, but not SHR

The one exception to this is the HD6500 which officially does not support SHR or RAID F1. It has `supportraidgroup="yes"` but does not have support_syno_hybrid_raid.

**Comment by pengkui** [comment]
FYI, my current setup is as follows:

DS3617xs, DSM 7.2, and `/etc.defaults/synoinfo.conf` has
```
supportraidgroup="no"
support_syno_hybrid_raid="yes"
```

**Screenshot of Storage Manager:**
![F1 and SHR](https://github.com/007revad/Synology_RAID-F1_SHR_switch/assets/751825/08c6ff14-7495-42d6-9568-167f36f9938a)
